font_family     	Monaspace Neon NF
bold_font           Monaspace Neon NF Bold
italic_font         Monaspace Neon NF Medium
bold_italic_font    Monaspace Neon NF Bold

font_size   		12
hide_window_decorations yes

window_margin_width 0
confirm_os_window_close 0

background_opacity 	0.88
cursor_shape		block
shell_integration  no-cursor
cursor_blink_interval 	0

background              #272a33
# black
color0                  #665c54
color8                  #7c6f64
# red
color1                  #d6367e
color9                  #ed39a2
# green
color2                  #2bc280
color10                 #34c957
# yellow
color3                  #d79921
color11                 #fabd2f
# blue
# blue
color4                  #9a5de8
color12                 #c074ff
# purple
color5                  #B0578D
color13                 #ED5AB3
# aqua
color6                  #78c4ad
color14                 #81d6a3
# white
color7                  #e8b8d4
color15                 #FED9ED
