;;; config/logbook.el -*- lexical-binding: t; -*-

(defvar toad/logbook-dir "~/org/journal/")
(defvar toad/daily-template (expand-file-name "daily_template.org" toad/logbook-dir))
(defvar toad/weekly-template (expand-file-name "weekly_template.org" toad/logbook-dir))

(defun toad/logbook-today-file ()
  (expand-file-name (format-time-string "%Y%m%d.org") toad/logbook-dir))

(defun toad/logbook-week-file ()
  (expand-file-name (concat "week-" (format-time-string "%Y-W%W") ".org") toad/logbook-dir))

(defun toad/read-template (file)
  "Read template FILE, replacing <DATE> with today's formatted date."
  (when (file-exists-p file)
    (with-temp-buffer
      (insert-file-contents file)
      (goto-char (point-min))
      (while (search-forward "<DATE>" nil t)
        (replace-match (format-time-string "%A, %d %B %Y")))
      (buffer-string))))

(defun toad/agenda-items-for-today ()
  "Collect TODO headings from agenda files scheduled for today."
  (let ((today-re (format-time-string "<%Y-%m-%d"))
        items)
    (dolist (file (org-agenda-files))
      (when (file-exists-p file)
        (with-temp-buffer
          (insert-file-contents file)
          (goto-char (point-min))
          (while (re-search-forward "^\\*+[ \t]+TODO[ \t]+\\(.*\\)" nil t)
            (let ((heading (match-string 1)))
              (save-excursion
                (forward-line 1)
                (when (and (< (point) (point-max))
                           (looking-at (concat ".*" (regexp-quote today-re))))
                  (push heading items))))))))
    (nreverse items)))

(defun log-today ()
  "Create today's log from daily_template.org. Pulls today's agenda items as side quests."
  (interactive)
  (let ((file (toad/logbook-today-file)))
    (if (file-exists-p file)
        (progn (find-file file)
               (message "today's log already exists"))
      (find-file file)
      (insert (or (toad/read-template toad/daily-template)
                  (concat "#+TITLE: " (format-time-string "%A, %d %B %Y")
                          "\n#+AUTHOR: toad\n\n* main quest\n** TODO \n* side quests\n** TODO \n* agenda\n** to learn\n*** TODO \n** to read\n*** TODO \n** to watch\n*** TODO \n* thoughts of the day\n** \n")))
      ;; inject agenda items under side quests
      (let ((items (toad/agenda-items-for-today)))
        (when items
          (goto-char (point-min))
          (when (re-search-forward "^\\* side quests" nil t)
            (end-of-line)
            (dolist (item items)
              (insert (format "\n** TODO %s" item))))))
      (save-buffer)
      (goto-char (point-min))
      (message "today's log created"))))

(defun log-open ()
  "Open today's log file if it exists."
  (interactive)
  (let ((file (toad/logbook-today-file)))
    (if (file-exists-p file)
        (find-file file)
      (when (y-or-n-p "no log for today — create one? ")
        (log-today)))))

(defun log-side-quest ()
  "Prompt for a side quest and add it to today's log."
  (interactive)
  (let ((quest (read-string "side quest: "))
        (file (toad/logbook-today-file)))
    (unless (file-exists-p file)
      (log-today))
    (find-file file)
    (goto-char (point-min))
    (if (re-search-forward "^\\* side quests" nil t)
        (progn (end-of-line)
               (insert (format "\n** TODO %s" quest)))
      (goto-char (point-max))
      (insert (format "\n* side quests\n** TODO %s\n" quest)))
    (save-buffer)
    (message "added: %s" quest)))

(defun log-thought ()
  "Add a timestamped thought to today's log."
  (interactive)
  (let ((thought (read-string "thought: "))
        (file (toad/logbook-today-file)))
    (unless (file-exists-p file)
      (log-today))
    (find-file file)
    (goto-char (point-min))
    (if (re-search-forward "^\\* thoughts of the day" nil t)
        (progn (end-of-line)
               (insert (format "\n** %s %s" (format-time-string "%H:%M") thought)))
      (goto-char (point-max))
      (insert (format "\n* thoughts of the day\n** %s %s\n" (format-time-string "%H:%M") thought)))
    (save-buffer)
    (message "thought logged")))

(defun log-weekly ()
  "Create this week's review from weekly_template.org."
  (interactive)
  (let ((file (toad/logbook-week-file)))
    (if (file-exists-p file)
        (progn (find-file file)
               (message "this week's review already exists"))
      (find-file file)
      (insert (or (toad/read-template toad/weekly-template)
                  (concat "#+TITLE: Week of " (format-time-string "%d %B %Y")
                          "\n#+AUTHOR: toad\n\n")))
      (save-buffer)
      (goto-char (point-min))
      (message "weekly review created"))))

(defun log-entry ()
  "Add a timestamped log entry to today's log."
  (interactive)
  (let ((entry (read-string "log: "))
        (file (toad/logbook-today-file)))
    (unless (file-exists-p file)
      (log-today))
    (find-file file)
    (let ((day-header (format-time-string "* %A, %m/%d/%y")))
      (goto-char (point-min))
      (unless (search-forward day-header nil t)
        (goto-char (point-max))
        (insert (format "\n%s\n" day-header))))
    (goto-char (point-max))
    (insert (format "** %s %s\n" (format-time-string "%H:%M") entry))
    (save-buffer)))

(defun log-streak ()
  "Show your consecutive logging streak."
  (interactive)
  (let ((streak 0)
        (date (time-subtract (current-time) (days-to-time 1))))
    (while (file-exists-p
            (expand-file-name (format-time-string "%Y%m%d.org" date) toad/logbook-dir))
      (setq streak (1+ streak))
      (setq date (time-subtract date (days-to-time 1))))
    (when (file-exists-p (toad/logbook-today-file))
      (setq streak (1+ streak)))
    (message "log streak: %d day%s" streak (if (= streak 1) "" "s"))))

(defun log-agenda ()
  "Show what's on the agenda for today in a buffer."
  (interactive)
  (let ((items (toad/agenda-items-for-today)))
    (if (not items)
        (message "nothing scheduled for today")
      (with-current-buffer (get-buffer-create "*today's agenda*")
        (erase-buffer)
        (org-mode)
        (insert (format "#+TITLE: agenda for %s\n\n" (format-time-string "%A, %d %B")))
        (dolist (item items)
          (insert (format "* TODO %s\n" item)))
        (goto-char (point-min))
        (pop-to-buffer (current-buffer))))))
