-- require("null-ls").setup({
-- 	sources = {
-- 		require("null-ls").builtins.formatting.prettierd.with({
-- 			filetypes = {
-- 				"javascript",
-- 				"javascriptreact",
-- 				"typescript",
-- 				"typescriptreact",
-- 				"vue",
-- 				"css",
-- 				"scss",
-- 				"less",
-- 				"html",
-- 				"json",
-- 				"jsonc",
-- 				"yaml",
-- 				"markdown",
-- 			},
-- 		}),
-- 		require("null-ls").builtins.formatting.stylua,
-- 	},
-- })
-- null-ls format on save function

vim.cmd("autocmd BufWritePre * lua vim.lsp.buf.format()")
